### ISSUE TITLE
Model Weights Incomplete

### ISSUE THREAD

**Issue by scando1993** [hongweilibran/wmh_ibbmTum#1]
Could you please upload all the weights, when I'm trying to make the decompress it says is missing one file z03. Please help me with the other files

**Comment by jstutters** [comment]
I'm seeing the same thing.  I tried opening the partial HDF5 file that can be extracted but get an error (using the h5py library).

**Comment by hongweilibran** [comment]
> Could you please upload all the weights, when I'm trying to make the decompress it says is missing one file z03. Please help me with the other files

Hello, sorry for the late response. I update some file and description. Please see the ReadMe.md. Just let me know if you have further questions. Email: hongwei.li@tum.de

**Comment by hongweilibran** [comment]
> c

Hello, sorry for the late response. I update some files and description. Please see the ReadMe.md. Just let me know if you have further questions. Email: hongwei.li@tum.de

**Comment by hongweilibran** [comment]
> I'm seeing the same thing. I tried opening the partial HDF5 file that can be extracted but get an error (using the h5py library).

I update some files and description. Please see the ReadMe.md. Just let me know if you have further questions. Email: hongwei.li@tum.de
