### ISSUE TITLE
WMH dataset

### ISSUE THREAD

**Issue by andys0975** [hongweilibran/wmh_ibbmTum#2]
Hello, I want to reproduce your results on WMH dataset, but I have waited the responses from the official email of MICCAI2017 challenge for two weeks. I wonder if you could share the download link?

**Comment by branbranbran** [comment]
> Hello, I want to reproduce your results on WMH dataset, but I have waited the responses from the official email of MICCAI2017 challenge for two weeks. I wonder if you could share the download link?

you meant the results on testing set??
The test set is hidden. You can send a dockerfile to the challenge organizer and get the result of your algorithm.

**Comment by branbranbran** [comment]
> Hello, I want to reproduce your results on WMH dataset, but I have waited the responses from the official email of MICCAI2017 challenge for two weeks. I wonder if you could share the download link?

Hello, did you send the signed agreement to Hugo (email: hkuijf@umcutrecht.nl ) ? Normally they will reply soon.

**Comment by andys0975** [comment]
Yey, I've sent signed agreement to official email two weeks ago. No responses since then. I'm not sure why.

**Comment by hongweilibran** [comment]
> Yey, I've sent signed agreement to official email two weeks ago. No responses since then. I'm not sure why.

you can cc Hugo (email: hkuijf@umcutrecht.nl )  at the meantime.
