### ISSUE TITLE
NPY files not available

### ISSUE THREAD

**Issue by VansFannel** [hongweilibran/wmh_ibbmTum#3]
Hi!

When I try to download your npy files to run the leave-one-subject-out experiments, the link https://drive.google.com/open?id=1m0H9vbFV8yijvuTsAqRAUQGGitanNw_k doesn't work. It said that the file has been moved to the trash.

Could you please restore it?

Thanks!

**Comment by FourierX9** [comment]
Hi!

The file slices_patient_id_label.npy is not available in the link. Is there any place that I can get it?

Thanks!
